import type { Metadata } from 'next'
import { Geist_Mono } from 'next/font/google'
import localFont from 'next/font/local'

import { Toaster } from '@/components/ui/sonner'
import { Providers } from '@/app/providers'

import '@/styles/globals.css'

import { cn } from '@/lib/utils'

const haffer = localFont({
  display: 'swap',
  src: [
    {
      path: '../fonts/Haffer.woff',
      style: 'normal',
      weight: '400'
    },
    {
      path: '../fonts/Haffer-Bold.woff',
      style: 'normal',
      weight: '700'
    }
  ],
  variable: '--font-haffer'
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn('h-auto antialiased', haffer.variable, geistMono.variable)}
      suppressHydrationWarning
    >
      <body className="h-full font-sans select-none bg-gray-50 dark:bg-zinc-950">
        <Providers>
          {children}
          <Toaster richColors />
        </Providers>
      </body>
    </html>
  )
}
